# Generated by Django 4.0.6 on 2022-07-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
